<section class="social-sharing-widget">
    <ul class="social-sharing">

        <li class="facebook-share social-share">
            <a href="<?= $block->getFacebookShare() ?>">
                <i class="fab fa-facebook-f"></i>
            </a>
        </li>

        <li class="google-share social-share">
            <a href="<<?= $block->getGoogleShare() ?>">
                <i class="fab fa-google"></i>
            </a>
        </li>

        <li class="twitter-share social-share">
            <a href="<?= $block->getInstagramShare() ?>">
                <i class="fab fa-instagram"></i>
            </a>
        </li>

        <li class="linkedin-share social-share">
            <a href="<?= $block->getLinkedinShare() ?>">
                <i class="fab fa-linkedin-in"></i>
            </a>
        </li>

    </ul>
</section>
