<section class="social-links-widget">
    <ul class="social-links">

        <?php if($block->getData('facebook')): ?>
            <li class="facebook-link social-link">
                <a href="<?php echo $block->getData('facebook');?>">
                    <i class="fab fa-facebook-f"></i>
                </a>
            </li>
        <?php endif; ?>

        <?php if($block->getData('instagram')): ?>
            <li class="instagram-link social-link">
                <a href="<?php echo $block->getData('instagram');?>">
                    <i class="fab fa-instagram"></i>
                </a>
            </li>
        <?php endif; ?>

        <?php if($block->getData('linkedin')): ?>
            <li class="linkedin-link social-link">
                <a href="<?php echo $block->getData('linkedin');?>">
                    <i class="fab fa-linkedin-in"></i>
                </a>
            </li>
        <?php endif; ?>

        <?php if($block->getData('youtube')): ?>
            <li class="youtube-link social-link">
                <a href="<?php echo $block->getData('youtube');?>">
                    <i class="fab fa-youtube"></i>
                </a>
            </li>
        <?php endif; ?>
        
    </ul>
</section>
